version: '3.1'

services:

  db_mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: welcome1 # replace with your root password
      MYSQL_DATABASE: pedidos # replace with your database name
      MYSQL_USER: dev # replace with your username
      MYSQL_PASSWORD: welcome1 # replace with your password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  db_mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev # replace with your root username
      MONGO_INITDB_ROOT_PASSWORD: welcome1 # replace with your root password
    volumes:
      - mongo_data:/data/db
    ports:
        - "27017:27017"

  artemis:
    image: vromero/activemq-artemis:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      DISABLE_SECURITY: "true" # for development only

volumes:
  mysql_data:
  mongo_data:
